version: "3"
services:
    api:
      build:       
        context: ./api
        dockerfile: Dockerfile-prod
      container_name: api-sonate
      ports:
       - "5001:5000" 
      depends_on:
        - mongo 
      restart: always
      networks:
        - sonate_net
      environment: 
        - NODE_ENV=production

    app:
      build:         
        context: ./front
        dockerfile: Dockerfile-prod
      container_name: front-sonate
      restart: always
      depends_on:
        - api
      ports:
       - "3001:80"
      networks:
        - sonate_net

    # api-dev:
    #   build: 
    #     context: ./api
    #     dockerfile: Dockerfile
    #   container_name: api-sonate-dev
    #   depends_on:
    #     - mongo
    #   ports:
    #    - "5000:5000"  
    #   restart: always
    #   networks:
    #     - sonate_net
    #   environment: 
    #     - NODE_ENV=development
    #   volumes:
    #     - ./api:/app/api
    #     - '/app/api/node_modules' 

    # app-dev:
    #   build: 
    #     context: ./front
    #     dockerfile: Dockerfile
    #   container_name: front-sonate-dev
    #   ports:
    #    - '3000:3000'
    #   restart: always
    #   depends_on:
    #     - api-dev
    #   networks:
    #     - sonate_net     
    #   environment:
    #     - NODE_ENV=development    
    #   volumes:
    #     - ./front:/app/front
    #     - '/app/front/node_modules'   

    mongo:
      image: mongo
      container_name: mongo-sonate-dev
      restart: always
      networks:
        - sonate_net
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: sonate
      volumes:
        - ./mongodb/datas/:/docker-entrypoint-initdb.d/

    mongo-express:
      image: mongo-express
      container_name: mongo-express-sonate-dev
      ports:
        - 8081:8081
      restart: always
      networks:
        - sonate_net
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
networks:
  sonate_net:
    driver: bridge
