version: "3"
services:
    api:
      build: ./api
      container_name: api-sonate
      ports:
       - "5001:5000"  
      restart: always
      networks:
        - sonate_net
      environment: 
        - NODE_ENV=production
    app:
      build: ./front
      container_name: front-sonate
      restart: always
      depends_on:
        - api
      ports:
       - "8085:80"
      networks:
        - sonate_net
networks:
  sonate_net:
    driver: bridge
